// Generated by gencpp from file beginner_tutorials/led_state.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_LED_STATE_H
#define BEGINNER_TUTORIALS_MESSAGE_LED_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct led_state_
{
  typedef led_state_<ContainerAllocator> Type;

  led_state_()
    : ledState()  {
    }
  led_state_(const ContainerAllocator& _alloc)
    : ledState(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _ledState_type;
  _ledState_type ledState;





  typedef boost::shared_ptr< ::beginner_tutorials::led_state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::led_state_<ContainerAllocator> const> ConstPtr;

}; // struct led_state_

typedef ::beginner_tutorials::led_state_<std::allocator<void> > led_state;

typedef boost::shared_ptr< ::beginner_tutorials::led_state > led_statePtr;
typedef boost::shared_ptr< ::beginner_tutorials::led_state const> led_stateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::led_state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::led_state_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::led_state_<ContainerAllocator1> & lhs, const ::beginner_tutorials::led_state_<ContainerAllocator2> & rhs)
{
  return lhs.ledState == rhs.ledState;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::led_state_<ContainerAllocator1> & lhs, const ::beginner_tutorials::led_state_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::led_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::led_state_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::led_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::led_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::led_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::led_state_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::led_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2e72d8d4579cf7ba2c7a9cea0cf0c7ab";
  }

  static const char* value(const ::beginner_tutorials::led_state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2e72d8d4579cf7baULL;
  static const uint64_t static_value2 = 0x2c7a9cea0cf0c7abULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::led_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/led_state";
  }

  static const char* value(const ::beginner_tutorials::led_state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::led_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string ledState\n"
;
  }

  static const char* value(const ::beginner_tutorials::led_state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::led_state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ledState);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct led_state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::led_state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::led_state_<ContainerAllocator>& v)
  {
    s << indent << "ledState: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.ledState);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_LED_STATE_H
